export const conversationsMock = [
  {
    _id: "c1",
    type: "p",
    name: "",
    owner_id: "u1",
    opponent_id: "u2",
    typing_users: [],
    draft: null,
    image_url: "",
    image_object: null,
    last_message: null,
    unread_messages_count: 0,
    updated_at: Date.now(),
  },
  {
    _id: "c2",
    type: "p",
    name: "",
    owner_id: "u3",
    opponent_id: "u5",
    typing_users: ["u3"],
    draft: { text: "draft message", replied_mid: null },
    image_url: "",
    image_object: null,
    last_message: null,
    unread_messages_count: 2,
    updated_at: Date.now(),
  },
  {
    _id: "c3",
    type: "g",
    name: "Developers",
    owner_id: "u1",
    opponent_id: null,
    typing_users: [],
    draft: null,
    image_url: "",
    image_object: null,
    last_message: null,
    unread_messages_count: 5,
    updated_at: Date.now(),
  },
  {
    _id: "c4",
    type: "p",
    name: "Bob Chat",
    owner_id: "u2",
    opponent_id: "u1",
    typing_users: ["u2"],
    draft: null,
    image_url: "",
    image_object: null,
    last_message: null,
    unread_messages_count: 0,
    updated_at: Date.now(),
  },
  {
    _id: "c5",
    type: "g",
    name: "",
    owner_id: "u3",
    opponent_id: null,
    typing_users: [],
    draft: null,
    image_url: "",
    image_object: null,
    last_message: null,
    unread_messages_count: 1,
    updated_at: Date.now(),
  },
];
